version: '3.4'

services:
  ecommerce.api.customers:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "6002:8080"

  ecommerce.api.orders:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "6003:8080"


  ecommerce.api.products:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "6001:8080"


  ecommerce.api.search:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - SERVICES__PRODUCTS=http://ecommerce.api.products:8080
      - SERVICES__CUSTOMERS=http://ecommerce.api.customers:8080
      - SERVICES__ORDERS=http://ecommerce.api.orders:8080
    ports:
      - "6004:8080"

